### ISSUE TITLE
[RFE] Export _all_ addresses configured

### ISSUE THREAD

**Issue by gfa** [craftyguy/networkd-dispatcher#1]
Hello

Currently only $ADDR is exported, which in my setup is my ip address, but i have no way to get my ipv6, could you expose it as separate variable? $IP6ADDR possibly

Also I noted that only the first address is exported, can you export them all? maybe in a different variable
like IPADDR_ALL and IP6ADD_ALL. This is vital for ipv6 

thanks

**Comment by craftyguy** [comment]
Thank you for the suggestion, I will take a look at implementing this soon!

**Comment by craftyguy** [comment]
Implemented in #2. Give it a try! I updated the readme to reflect the array names.
