### ISSUE TITLE
AUR PKGBUILD should have arch=( any )

### ISSUE THREAD

**Issue by charles-dyfis-net** [craftyguy/networkd-dispatcher#16]
Presently `arch=( i686 x86_64 )`, but no element of the software is architecture-specific.

**Comment by charles-dyfis-net** [comment]
(I'd also consider making `wireless-tools` an optional dependency, since we get along fine without it as long as no wlan interfaces exist).

**Comment by craftyguy** [comment]
arch=(any) makes sense, I will change that for the next release.

I'll have to think about how to handle wireless-tools.. 
If it's optional, not installed, and a user has wlan interfaces, get_wlan_essid will blow up. One way to resolve that is to revert  fe4d8e68572a552820c1cb355539b363bd13a1b4 , then if IWCONFIG is None it can be handled and we don't need to make sure that IWCONFIG is *actually* valid in get_wlan_essid.

I probably should have asked before merging, but is fe4d8e68572a552820c1cb355539b363bd13a1b4 resolving a specific issue you encountered?

**Comment by charles-dyfis-net** [comment]
fe4d8e6 was preventing me from doing light testing on a non-Linux platform.

The other thing is that frankly, I'm kinda' offended by the `resolve_path` function in general. Hardcoding paths to a limited list means that your software won't work on distros that don't match exactly what you expect. Put `networkctl` in `/sbin` instead of `/bin` or `/usr/bin`? Boom! Install a local copy of `iwconfig` under `/usr/local`? Nope, not going to get honored; etc.

And for test purposes, honoring the `PATH` means one can provide shims -- ie. put a `test/bin/iwconfig` in the codebase and have it return arbitrary data.

Now, if you'd want `resolve_path` to still exist but do an actual PATH lookup rather than use a different hardcoded list of locations per service -- I'm fine with that, and I think defaulting to None (and handling the case) is fine.

**Comment by charles-dyfis-net** [comment]
(Happy to take the implementation if you'd prefer).

**Comment by craftyguy** [comment]
I see. Yea, I'm not super happy with resolve_path, it was inherited
from the project I originally forked this one, and I haven't gotten
around to 'doing it correctly'. I'll take a shot at that later on.

**Comment by charles-dyfis-net** [comment]
Made a quick attempt at it myself in 49cfffa1bc5412e300d7fedc6c353c560ab658b4.

**Comment by craftyguy** [comment]
Ah, just as I was starting to make progress on this.. you're doing it too fast ;)

**Comment by craftyguy** [comment]
Updated PKGBUILD when I cut the 1.4 release a few minutes ago:

- arch=('any')

- wireless_tools is an optional dependency
