### ISSUE TITLE
Allow triggers on AdministrativeState, as opposed to only OperationalState

### ISSUE THREAD

**Issue by charles-dyfis-net** [craftyguy/networkd-dispatcher#18]
At present, networkd-dispatcher operates only on operational states -- `off`, `no-carrier`, `dormant`, `carrier`, `degraded` and `routable`.

systemd-networkd also tracks administrative states: `pending`, `configuring`, `configured`, `unmanaged`, `failed`, `linger`.

These do not have a 1:1 mapping: In particular, `routable` can happen before `configured` is reached. `routable` indicates that *at least one address* which is neither site-, link- or host-only is associated with the given interface; whereas `configured` indicates that **all** addresses are ready.

At minimum, a hook for `configured` should be added, to allow scripts to fire only after *all* addresses associate with an interface are assigned.

**Comment by craftyguy** [comment]
This is actually a REALLY good idea.. I was trying to figure out how to wait until the op state 'settled' before running scripts, and was unaware of the administrative States until now. I'll take a shot at implementing this.

**Comment by charles-dyfis-net** [comment]
If you run with `-vv` (DEBUG logging), it'll make the administrative states a bit more visible.

**Comment by craftyguy** [comment]
I noticed those when testing your PR to enable logging, but didn't put the two (admin state & op state status) together

**Comment by charles-dyfis-net** [comment]
BTW, are you working on this one actively? I might take it myself, if not.

**Comment by craftyguy** [comment]
Yea I'd like to take a stab at it, but it won't be until late Friday/saturday

**Comment by charles-dyfis-net** [comment]
See PR #19.

**Comment by craftyguy** [comment]
Well I guess I won't be taking a stab at it now. Thanks for the PR, I'll review/merge this weekend.
