### ISSUE TITLE
Race condition when addition and removal of network devices happens quickly one after the other

### ISSUE THREAD

**Issue by MarkJonas** [craftyguy/networkd-dispatcher#20]
If one network device is added and quickly afterwards another network device is removed, the following can happen:

1. New device NEW is plugged in.
1. Existing device OLD is removed.
1. Reception of state change message 'administrative=unmanaged' for newly added device NEW.
1. List of device is updated. OLD is not on the list any more. NEW is now on the list.
1. Script for device NEW is run.
1. Reception of state change message 'administrative=linger' for removed device OLD.
1. Look-up of device OLD fails because it is not on the list anymore. => no script is run

At the last point the desired behaviour would have been that the linger script is called. It is not called because the device list is updated via *networkctl* before.

I am wondering why the device list is updated via *networkctl* every time a device is not found in it. I understand that the device list needs to be initialized at startup, but wouldn't it be better to only update the list according to received signals?

For example:
- If a device goes into linger, it is removed from the list.
- If a signal is received for a device which is not on the list, it will be added to the list with *administrative=invalid* and *operational=invalid*.
- After processing the signal the state is updated in the list. (IMHO this already happens in the code.)

**Comment by charles-dyfis-net** [comment]
This is a good catch, thank you.

To answer your question about the *why* of rereading the list in full --

The issue is that received signals refer to devices by their integer indexes. Receiving a signal with an unknown index, then, doesn't provide a device name -- and doesn't provide sufficient information to update the list to *add* that name without out-of-band investigation.

If device indexes are never reused (which, as someone with a hotplugging environment, you're well-positioned to investigate), perhaps updates can be made additive, leaving old values in place?

**Comment by MarkJonas** [comment]
You are right, the signal does not contain the device name. So *networkctl* will be needed for making this lookup. But maybe it could be limited to that.

I am pretty sure that the indices are not re-used. At least not immediately. I plugged and unplugged a CAN-USB box multiple times and every time I got a new index, each time incremented by one. I tried it with index 5 to 21.

Of course, at some point there will be an overflow. If it is an integer that might take very long to hit that boundary. On top, the netword-dispatcher would remove an entry from the internal list after receiving a linger signal, there would be no collision at all.

Although CAN-USB boxes are expensive, Ethernet-USB adapters are cheap, e.g. on eBay.

**Comment by charles-dyfis-net** [comment]
Good deal, then -- that gives us a straightforward path towards implementing a fix. My ability to work on networkd-dispatcher during daytime hours is limited to fixes with utility to my employer, and we don't use hotplug support -- but I'll throw something together during off-hours as soon as opportunity permits, if you or @craftyguy don't get there first.

**Comment by craftyguy** [comment]
@MarkJonas 
Thanks for reporting this! [Looking at networkctl.c, iface index is just a regular ol' int](https://github.com/systemd/systemd/blob/master/src/network/networkctl.c#L134), so technically it would overflow if they aren't actively preventing it on assign (I didn't check), but it shouldn't be a problem on any modern architectures (x86 [signed] int is 4 bytes, etc)

I do not have a good way to test this though, as the interfaces in my system are fixed. I'll try experimenting with unloading/loading the LKM for my NIC to see if it gives the same behavior so I can validate a patch for this issue.

**Comment by craftyguy** [comment]
So my method of testing was basically creating  and deleting a network bridge :)

@MarkJonas give the fix in [the fix_20 branch](https://github.com/craftyguy/networkd-dispatcher/tree/fix_20) a try and let me know if it helps with this issue!

This patch will keep old iface indexes around indefinitely, or at least until networkd-dispatcher is restarted (may cause issue with overflow as stated previously), but maybe that's ok for now. @charles-dyfis-net, if you disagree then we can discuss more before I merge this patch into master.

**Comment by charles-dyfis-net** [comment]
If we implemented Mark's proposal of clearing items for which we've received a signal with `administrative=linger` it would both resolve the overflow case and prevent memory use from increasing over time, so that's definitely an outstanding improvement, but I agree that on its own the fix_20 approach should address the immediate issue, and that we're better off with than without it.

**Comment by craftyguy** [comment]
I would appreciate it if someone could help with testing [the branch where this is implemented/fixed](https://github.com/craftyguy/networkd-dispatcher/tree/fix_20) before I merge it!
