### ISSUE TITLE
Env. variables AdministrativeState and OperationalState not populated

### ISSUE THREAD

**Issue by gspe** [craftyguy/networkd-dispatcher#23]
When you update the environmental variables in the code you have
```
# Set script env. variables
        script_env = dict(os.environ)
        script_env.update({
            'ADDR': (data.get('Address', ['']) + [''])[0],
            'ESSID': data.get('ESSID', ''),
            'IP_ADDRS': ' '.join(v4addrs),
            'IP6_ADDRS': ' '.join(v6addrs),
            'IFACE': iface.name,
            'STATE': str(state),
            'AdministrativeState': data.get('AdministrativeState', ''),
            'OperationalState': data.get('OperationalState', ''),
            'json': json.dumps(data),
        })
```
but data dictionary doesn't contain AdministrativeState and OperationalState keys
this is my  json.dumps(data)

```
json:
{"Type": "ether",
"State": ["routable (configured)"],
"Link File": ["/usr/lib/systemd/network/99-default.link"],
"Network File": ["/etc/systemd/network/20-wired.network"],
"Path": ["pci-0000:00:19.0"],
"Driver": ["e1000e"],
"Vendor": ["Intel Corporation"],
"Model": ["82579V Gigabit Network Connection (P8P67 Deluxe Motherboard)"],
"HW Address": ["c8:60:00:e3:5c:4d (ASUSTek COMPUTER INC.)"],
"Address": ["192.168.0.109", "fe80::ca60:ff:fee3:5c4d"],
"Gateway": ["192.168.0.1", "fe80::2c72:1ff:fea7:b982 (TP-LINK TECHNOLOGIES CO.,LTD.)"],
"DNS": ["84.200.69.80", "84.200.70.40"]}

```

**Comment by craftyguy** [comment]
What is the output of: `networkctl list --no-pager --no-legend` when $json does not contain administrative or operational state?

Also, are you using the latest networkd-dispatcher from git or one of the packaged/posted released versions?

**Comment by gspe** [comment]
I'm using the version present on AUR

```
gspe@jura /e/s/system> networkctl list --no-pager --no-legend
  1 lo               loopback           carrier     unmanaged 
  2 wlp7s0           wlan               off         unmanaged 
  3 eno1             ether              routable    configured

```

**Comment by craftyguy** [comment]
Ah, it is because I have not cut a release yet with this commit in it 0f4b9929c4ecef718a45b6a7c6256dab9b455b29, which separates the "State" json value to 'administrative' and 'operational' states.

Since this is the only commit to master since the latest version in AUR, and I feel pretty comfortable that this commit has been tested, I'll go ahead and do a new release now and push it to AUR. Stand by!

**Comment by craftyguy** [comment]
Ok, version in AUR (now 1.5) has been updated to include this functionality. This should resolve the issue you reported here, however if it doesn't then please re-open & provide more info. Cheers!
