### ISSUE TITLE
debian packaging: package stability, manpage

### ISSUE THREAD

**Issue by dario23** [craftyguy/networkd-dispatcher#25]
i quite like this package, and was wondering whether you'd consider it ready for packaging in a more stable-oriented distro like debian (which i'm using, there are others as well i guess).

i don't think packaging for debian would require any changes, except maybe they'd be happy if there was a manpage for networkd-dispatcher

i'd be willing to do all the packaging-related work if you think the package is stable enough and will be there for the forseable future, just wanted to ping here first before doing unneccessary work (e.g. you're planing on abandoning/rewriting it already etc.).

**Comment by craftyguy** [comment]
Hi! I like this suggestion, but I do not have any systems with Debian so I'd have to rely on you to do packaging/testing/maintaining of a deb package.

I'm not planning on abandoning this project, I still use it every day on my systems. In terms of 'how stable', there are some open issues now that I need to find time to resolve before I would consider it to be stable, but I'm afraid that the amount of testing I am able to perform does not cover all possible usage models or interfaces that this tool could come across "in the wild"...

**Comment by craftyguy** [comment]
@dario23 
Have you tried packaging this for Debian? If so, do I need to make any additional changes to help out with supporting this?

**Comment by ryu0** [comment]
I made a pull request to include a set of files for Debian source packages. From there it is a trivial matter to create a Debian binary package.

**Comment by craftyguy** [comment]
@ryu0 was kind enough to submit some changes that should make this app friendlier for anyone that would like to maintain a debian package. 

As mentioned previously, I have no plans to abandon this project nor perform any massive re-writes. I reserve the right to re-write how certain methods are implemented, but I will not be making any changes to the external interfaces (e.g. variable names passsed to scripts, locations of scripts, etc) unless I absolutely have to. If/when that time comes, I'll step the major version # to 2.x to indicate that it's not backwards compatible with config from 1.x.

Regarding stability of the app, it "works for me" and at least one other user I know of (@charles-dyfis-net). That's not a great method to measure stability though. So I have started to slowly write unit tests (using pytest), and have enabled Travis CI to test PRs, commits, and branches to this project. If you have other ideas that would help out, I'd be more than happy to listen.

I'll close this ticket, but if you have other concerns/questions about this topic, don't hesitate to let me know!
