### ISSUE TITLE
Question / request: Example of establishing VPN connection on up/down (e.g. suspend/resume)

### ISSUE THREAD

**Issue by jonascj** [craftyguy/networkd-dispatcher#26]
You mention opening a VPN connection as a use case, would you mind giving an example of such?
I'm trying to have execute `systemctl start openvpn@config.service` when first establishing connection after boot and `systemctl restart openvpn@config.service` on resume (from suspend).

So far I've only found the routable (scripts in routable.d) state to be reached after resuming, but even with the -T option I do not see the routable state after boot.

Could you share an simple example or explain when to expect the states (off, dormant, no-carrier, routable) to be reached (I assume you must have knowledge of this after writing networkd-dispatcher)?

Cheers, Jonas

**Comment by jonascj** [comment]
I managed to do something useful enabling openvpn-client (`systemctl enable openvpn-client@my.conf`) which cause it to be started on boot, and then restarting openvpn with `systemctl restart openvpn-client@my.conf` in an `/etc/networkd-dispatcher/routable.d/10-restart-openvpn-client`, which checks against $IFACE to prevent restarting openvpn when the tun0 adapter becomes routable.

I still think it is a fine idea to include some examples somewhere.

**Comment by craftyguy** [comment]
Hey, sorry, I've been meaning to post an example here for you but the system I use with openvpn is not available right now.

Yea, I basically restart openvpn on the `routable` event. I even implemented a 'network blacklist' since I don't want the openvpn client to be running on certain networks.

I'll post my configuration once my system is available, sorry again!

**Comment by jonascj** [comment]
No need to be sorry, thank you for the quick reply and very useful script/package!
Of course I'm interested in the OpenVPN example, but I also think it would be useful to have a bit more documentation/examples on the states (off, dormant, no-carrier, routable), e.g. when should one expect to see them?

For example I'm confused as to why I do not see any routable event after boot (on my wlan or lan interface). Not even with the -T switch/argument. The -T cause off and dormant to be seen after boot, presumably from the previous shutdown.

If you have the information that is of course, or some pointers into the systemd docs.

**Comment by craftyguy** [comment]
Hi! I have put my openvpn client script on the wiki: https://github.com/craftyguy/networkd-dispatcher/wiki/Examples

> For example I'm confused as to why I do not see any routable event after boot (on my wlan or lan interface). Not even with the -T switch/argument. The -T cause off and dormant to be seen after boot, presumably from the previous shutdown.

-T will cause the service to process existing interfaces in the current states they are in when it (the service) starts. When you see `off` and `dormant`, are these interfaces listed as `routable` if you run `networkctl` ?

**Comment by jonascj** [comment]
Hmm, I can no longer replicate what I reported about a difference in the events detected with and without `-T`. 
And now I also see an routable event/update on boot. Is there a race condition; whether the networkd-dispatcher service starts before the interface becomes routable or not?

**Comment by craftyguy** [comment]
Technically there shouldn't be (unless there's a bug), starting with
-T will allow processing interfaces in the state they are in when the
service starts, and if state changes after the service starts then it
would get caught by the service and the new state would get processed
there. For instance, if an interface is 'off' when service starts with
-T, and then the interface changes to 'routable' at some point after.

**Comment by jonascj** [comment]
But without the `-T` option there is a "race condition", i.e. the networkd-dispatcher could start after the interfaces becomes routable (or any other state) and the event missed?

**Comment by craftyguy** [comment]
That's correct, if an interface becomes routable *before* networkd-dispatcher starts, and it is started *without* the `-T` option, then no action is taken for that interface in the routable state. Of course if that interface goes offline and then becomes routable again (after networkd-dispatcher starts), then actions relevant to those events would be processed.

Whether or not it's a "race condition" depends on your expectations :)

**Comment by jonascj** [comment]
Agreed, the label "race condition" depends on expectations.
Let us close this for now. If I see the problem of no "routable" event/update on boot (with -T) I'll open a new issue. 

Also thank you for the example, it is almost the same I do in a shell script, except I only ever restart on 'routable', openvpn-client@my.conf 'enabled' ensured it starts on boot.
