### ISSUE TITLE
Starts too late during boot

### ISSUE THREAD

**Issue by julian-klode** [craftyguy/networkd-dispatcher#40]
networkd-dispatcher has default dependencies and thus starts very late and misses events from networkd during earlier boot. We should probably mirror systemd-networkd's after dependencies, and start before it:

```
DefaultDependencies=no
After=systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
Before=systemd-networkd.service
```
@craftyguy  What do you think?

Originally reported at: https://bugs.launchpad.net/ubuntu/+source/networkd-dispatcher/+bug/1772137

**Comment by julian-klode** [comment]
Maybe we should also replace the `WantedBy=multi-user.target` by `WantedBy=systemd-networkd.service` so we only start it if we are starting systemd-networkd.service.

**Comment by craftyguy** [comment]
@julian-klode 

Take a look at 87e5541. On Arch Linux, I had to also specify `dbus.service` in the `After=` line to make sure it didn't try to start before dbus was up and running. This seems to work well on Arch, but I don't have a Ubuntu system to test on. Feel free to re-open this issue if this needs more work.

Thanks for the idea!

**Comment by julian-klode** [comment]
Looks good, I wonder if 

```
Wants=dbus.socket
After=dbus.socket     
```

(as systemd-logind and dbus-org.freedesktop.login1 seem to do here; though fwupd and wpa_supplicant use your approach) would be nicer, though. It at least says that you need dbus. Both probably work, as dbus starts in the same target.
