### ISSUE TITLE
Provide startup-time feedback

### ISSUE THREAD

**Issue by charles-dyfis-net** [craftyguy/networkd-dispatcher#8]
At present, systemd does not know when networkd-dispatcher has finished startup and is listening for new events. This prevents a configuration from being established which avoids races (as by preventing systemd-networkd from starting up until networkd-dispatcher has fully initialized).

The `sd_notify` socket mechanism should be supported to allow networkd-dispatcher to be configured as a service with `Type=notify` rather than `Type=simple`, such that it can provide feedback to systemd when initialization is complete.

**Comment by craftyguy** [comment]
Great idea. This should be implemented in such a way that there's not an added requirement for this project that users have/use systemd (e.g. fail gracefully if systemd is not present). 

I'll take a stab at this in a different branch, and would appreciate any feedback you have once I get it posted!

**Comment by charles-dyfis-net** [comment]
With respect to the toggle -- looking at whether the `SD_NOTIFY` environment variable is set should suffice to disable this on non-systemd systems (or systemd systems without the control socket enabled).

**Comment by craftyguy** [comment]
@charles-dyfis-net: I took a shot at implementing this, you can see it in the [add_sd-notify](https://github.com/craftyguy/networkd-dispatcher/tree/add_sd-notify) branch. I also changed the default type in the service file from 'simple' to 'notify', and the service is successfully notifying systemd that it is running. 

I'm going to test this more with a system I have that heavily uses this program before I merge this branch into master, but would appreciate any comments/feedback you have!

**Comment by charles-dyfis-net** [comment]
LGTM as-amended.

**Comment by craftyguy** [comment]
Implemented now, thanks for the suggestion and for the help reviewing!
