### ISSUE TITLE
Provide option to run triggers for preexisting interface states

### ISSUE THREAD

**Issue by charles-dyfis-net** [craftyguy/networkd-dispatcher#9]
At present, startup-time race conditions can cause triggers not to be invoked.

One approach to addressing this is to *always* run triggers appropriate to the state that network interfaces are already in at the point in time when networkd-dispatcher is invoked.

**Comment by charles-dyfis-net** [comment]
@craftyguy, ...to be clear, I'm willing to implement this (and prior ticket) myself, but would appreciate your feedback first.

**Comment by craftyguy** [comment]
Sure, I appreciate the ideas/requests! 

I think since some folks (myself included, on at least one system I use this on) wouldn't want this behavior to be enabled. This means that I need to get around to implementing a configuration file for this program, so this option (and others) can be toggled in a persistent manner. I want to have this (the config file) in place before merging this request. 

I may also want to put off adding #8 until then as well, so it can be a config option (e.g. "systemd-present=(y/n)", but I'm less convinced that would need to wait for a config file.

On an unrelated note, you're filing a lot of really good stuff here, and I'm curious how you are using this project.. if you don't mind saying.. it's motivating to hear that folks are getting some use out of the random projects post here :)

**Comment by charles-dyfis-net** [comment]
Is there any particular reason to go for a config file, vs a command-line option? My assumption is that this is going to be invoked via some kind of process supervision mechanism (whether systemd or not), and thus that command-line arguments will themselves be pulled from config files.

**Comment by charles-dyfis-net** [comment]
(BTW, re: discussing my use cases, I'd want to do that offline. I'm charles@dyfis.net; feel free to ping via Hangouts, or contact via +15123943516 via Signal. This comment will self-destruct).

**Comment by craftyguy** [comment]
@charles-dyfis-net my reasoning is that a config file is much more readable/user friendly than command-line options (even ignoring the long vs. short form arguments). It also makes the system admin's wishes the default behavior, regardless of whether they forget to invoke the program with all the right command-line options in place. In addition, it removes any ambiguity around what the "default" options are before running the program, and makes backup/restore of those options rather simple.

**Comment by charles-dyfis-net** [comment]
This tooling *is* your baby, but I strongly disagree.

- Defaults are *entirely* relevant (and not at all obvious) when a new version of software is used with a configuration file written against an older version (which is how things end up working out *in practice* with config files deployed through config automation software -- Chef, Ansible, SaltStack, etc).
- Modern Python tooling (argparse, etc) entirely addresses the long-vs-short matter, *and* supports printing defaults in `--help`, making that information internal to the software itself, rather than its shipped default config files or documentation.
- Default configuration files left in place or modified by hand (or via the machinations of a software packaging system's decisions about when to leave a config file in place vs when to override it during an upgrade) are *less* likely to be backed up than content applied through a configuration management system.

**Comment by craftyguy** [comment]
All really good points that I hadn't considered, so I appreciate the new perspective. Let me noodle on it a little more. 

For this particular request I'm inclined to make this behavior, triggering on current state on start, disabled by default but the user can opt to enable it (either through cmdline opt or config file.. TBD!).

**Comment by charles-dyfis-net** [comment]
(And then the longer-term stuff: It's easy to conditionally automate the arguments a program is invoked with, but hard to determine a config file's contents at runtime).

**Comment by craftyguy** [comment]
Should be implemented now with your PR #11
